# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 732af8aeea78a03466384d50e93bea5a7822bab73b73832b846821f945c89f73b5740b211c37aac4ffb2ea844bffa14dce4ad792265ffe5f22ba9cb11f106f7c

test:
  secret_key_base: f205957581c418c982d9635d6f6af3b311be11e0785e9e2790f9ad11f218c4c41c444e6c2cec74ce25907a555ecc00f8972a16a006413c05c6c3c71653632992

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
